---
title: "DC Crime Map"
subtitle: "Developing Data Products Week 2"
author: "Neil Kutty"
date: "May 20, 2017"
output: html_document
---

####A Rendered Leaflet Map Plotting the Last 30 Days of Crime Incidents in Washington, D.C.

**Clicking on Individual Clusters will zoom the cluster. Clicking on individual markers will provide additional detail on the incident ** 

data: DC Crime - Last 30 Days [Open Data DC](http://opendata.dc.gov/datasets)



```{r setup, include=TRUE, eval=TRUE, message=FALSE, warning=FALSE, echo=FALSE}
library(dplyr)
library(tidyr)
library(jsonlite)
library(lubridate)
library(leaflet)
library(ggplot2)
```




```{r cleandata, eval=TRUE, echo=FALSE}
# Fig. 1 

########---------------------------------------------------------------------#>>>
  ## Retrieve the data in JSON format from opendata.dc.gov using fromJson()
  dccrimejsonlite <- fromJSON('http://opendata.dc.gov/datasets/dc3289eab3d2400ea49c154863312434_8.geojson')
  ## use cbind() combine the list elements and create a dataframe
  dc_crime_json <- cbind(dccrimejsonlite$features$properties,dccrimejsonlite$features$geometry)

  ## Seperate and clean lat/long columns but keep original datetime column
  ## --also separate REPORTDATETIME column
  dc_crime_clean <- dc_crime_json %>% 
    separate(coordinates, into = c("X", "Y"), sep = ",")%>%
    separate(REPORTDATETIME, into = c("Date","Time"), sep="T", remove = FALSE)%>%
    mutate(Weekday = weekdays(as.Date(REPORTDATETIME)),
           DATETIME = ymd_hms(REPORTDATETIME, tz='America/New_York'),
           Date = as.Date(Date),
           X = as.numeric(gsub("c\\(","",X)),
           Y = as.numeric(gsub("\\)","",Y)))

```


#### Render the leaflet map

```{r map, eval=TRUE}
points <- cbind(dc_crime_clean$X,dc_crime_clean$Y)
leaflet() %>%
  addProviderTiles("OpenStreetMap.Mapnik",
                   options = providerTileOptions(noWrap = TRUE)
  ) %>%
  addMarkers(data = points,
             popup = paste0("<strong>Report Date: </strong>",
                            dc_crime_clean$DateClean,
                            "<br><strong>Offense: </strong>", 
                            dc_crime_clean$OFFENSE, 
                            "<br><strong>method: </strong>", 
                            dc_crime_clean$METHOD,
                            "<br><strong>shift: </strong>",
                            dc_crime_clean$SHIFT,
                            "<br><strong>blocksite address: </strong><br>",
                            dc_crime_clean$BLOCKSITEADDRESS
             ),
             clusterOptions = markerClusterOptions()
  ) 

  
```
